# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 03 Dec 2022 13:36:14 +0000
*               @ALL          0
*               @user         8
