# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 03 Dec 2022 13:36:14 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

norwagov:$2y$10$CSSTOtkYtUs1bOmHKUvqbOzSpkLM4arf3Vhk4JW49E/C.LnJC7HKq:Piotr Gawron:norwagov43@gmail.com:admin,user
newq:$2y$10$MkGcXMW1lNB118ErnxLBxOn6L8q1rQFvD.jMrodqkVqhtXacoPgYS:noe:ns@e:user
norwagov2:$2y$10$eYfY1rXn4e1iPv53pBTGsOHNWYrL16m827PfczeiQjcl6XRFtmmQa:norwagov2:piotr.firma@incs.pl:user
